### ISSUE TITLE
support sending proper batches to EventBridge

### ISSUE THREAD

**Issue by agebhar1** [awslabs/eventbridge-kafka-connector#26]
## What is your idea?
Sending proper batches to EventBridge w.r.t. 256kb size limit.

## Would you be willing to make the change? 
Yes.

**Comment by baldawar** [comment]
oh that would be great. its on @embano1 's wishlist for sure. I believe this part of the code needs to measure how big the payload sizes are https://github.com/awslabs/eventbridge-kafka-connector/blob/main/src/main/java/software/amazon/event/kafkaconnector/EventBridgeWriter.java#LL123C1-L123C89. You can see an example way to calculate size at https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-putevent-size.html . This code can be modified to make sure all batches of events are at most 256KB .

**Comment by embano1** [comment]
Thx for bringing this up @agebhar1 ! That's definitely something we should add soonish...

Looping in @maschnetwork since he also had thought about this.
Let me dump a quick list of things I'd like to see us tackle here:

- [ ] Replace Guava dep w/ own implementation (it's literally just doing batches, but a huge dep)
- [ ] Use Rishi's link as guidance but let's review this article (based on a code proposal) as it's a bit dated - we might want to update the docs based on the implementation we settle on here
- [ ] We definitely need to add several unit and integration tests for this change

We're happy to help you through this!

**Comment by maschnetwork** [comment]
Thanks for adding this @agebhar1.

My initial thought was to create a custom **EventBridgeBatchedItemCollector** that implements the [Collector](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collector.html) Interface. We could then check for both BatchSize of 10 (Max EventBridge Batch Size) + Max Payload Size in the collector and produce proper batches. The result would be a `List<List<PutEventsRequestEntry>>`. Which we can leverage [here](https://github.com/awslabs/eventbridge-kafka-connector/blob/e4854e62d12cfea516cab6a681e68521d2b043d0/src/main/java/software/amazon/event/kafkaconnector/EventBridgeWriter.java#L129). This would also allow us to remove the need for Guava's Lists.partition and we can remove the lib. Also it makes testing quite easy.

**Comment by agebhar1** [comment]
Thanks for the fast reply @baldawar, @embano1 and @maschnetwork also for the hints.

I came up with the same idea @maschnetwork to implement Javas Collector interface for a size based reduction to list of list. Unfortunately the mentioned [PutEvents](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-putevent-size.html) is generated later at https://github.com/awslabs/eventbridge-kafka-connector/blob/e4854e62d12cfea516cab6a681e68521d2b043d0/src/main/java/software/amazon/event/kafkaconnector/EventBridgeWriter.java#L183-L197 which makes it harder to calculate the size while collecting. But there are a couple of ways to solve it.

@embano1, I support dropping the Guava dependency since its the only function used from the library :+1:.

What makes me wonder is why `PutEvents` does not have a property/method to get the actual size and it's documented as non runable code. I can think of that would be nice to have the information on the object which is aligned with the EventBridge serialization.

**Comment by embano1** [comment]
I agree that this would be desirable instead of creating bespoke size estimations. Not sure how the SDKs are generated and how those helper methods can be implemented (if at all). cc/ @baldawar

**Comment by baldawar** [comment]
I think we'll probably need to do something similar to this code https://github.com/aws/aws-sdk-java-v2/blob/ad1f232de73e328a0a5c83c8a4d924baec7026ec/utils/src/main/java/software/amazon/awssdk/utils/IoUtils.java#L43

**Comment by agebhar1** [comment]
Hi @baldawar, @embano1 and @maschnetwork! I walked through the code to get an idea for a good place and structure for calculating the batches.

I'd like to propose some structural changes (first) for discussion. The Kafka [Connect JDBC Connector](https://github.com/confluentinc/kafka-connect-jdbc) has a similar class structure but it's in the database context. A record is _written_ to a database, hence it's called `*Writer`. In the EventBridge context the record is transformed to an event and _send_ to the EventBridge. The name `*Writer` does not fit best IMHO. I can think more of an **adapter** with an interface like:
```
public Result put(Collection<SinkRecord> records)
```
where `Result` contains the failed and successfully send `SinkRecords` separated. Currently the wrapper/adapter `EventBridgeWriterRecord` is mutable with a dedicated state of the send result. You're using the Java Streams API and promote a function style, so immutability might fits better. If we handle the conversion of a Kafka `SinkRecord` to an EventBridge `PutEventsRequestEntry` inside the writer (adapter/sender) before batching it's then possible to do proper batch size calculation.

WDYT  :smiley:

**Comment by maschnetwork** [comment]
Hi @agebhar1,

effectively we are "writing" records to EventBridge. Hence the naming "Writer" + given the fact we are in a Sink context. We could argue we are publishing events so we could also go with *Publisher, but at this point I don't think it is misleading that it needs an immediate action. However, I do agree with the interface contract. In the initial design the WriterRecord did not contain the full SinkRecord and there are multiple occasions where a record can get into error state - the mutability evolved from there but now in the context of the new batching logic I think it makes sense to refactor it. I agree with your proposals + adapted a few details. To summarize:

1. EventBridgeWriter will accept a Collection of SinkRecords rather than EventBridgeWriterRecords.

` public EventBridgeWriterResult putItems(List<SinkRecord> records)`

2. The return type of this method should be a new class EventBridgeWriterResult containing a) List<SinkRecord> successfulRecords b) List<EventBridgeWriterErrorRecord> errorRecords, which can be just the current EventBridgeWriterRecord renamed to EventBridgeWriterErrorRecord. Instead of having this class mutable the error code and status should be accepted in the constructor.

```  
public EventBridgeWriterErrorRecord(SinkRecord sinkRecord, String errorCode, String errorMessage) {
    this.record = sinkRecord;
    this.errorCode = errorCode;
    this.errorMessage = errorMessage;
  }
```

3. Batching can then happen in the writer and loop from the task can be removed / moved to the Writer. This makes sense since the batching number of 10 is a detail of the EventBridge implementation and ideally must not be known by the task. We already agreed in the previous answers that a custom Collector implementation would be a good approach (Checking for max items of 10  + size)

```
var batches = records.stream()
       .map(this::createPutEventsEntry)
        //Todo: filter error records
       .collect(EventBridgeBatchedItemCollector.collect());

//Loop batches
```

5. After this step we can also remove Guava.
6. Thought: `createPutEventsEntry` can also cause the record to be in an error state - it might make sense to deal with the new result class already in the context of this transformation  to be able to filter the invalid records before sending to EB - currently this is done with an Optional.

I think it makes sense to split those changes over multiple PRs. I'm happy to support you on this. Wdyt?

**Comment by agebhar1** [comment]
Hi @maschnetwork,

`*Publisher` sounds great but I'm fine with the current naming too, if it doesn't mislead anyone. Fully agree with all the steps and class name `EventBridgeWriterResult`.

Should I create a new issue for the refactoring @embano1 or is a PR sufficient? I plan to do the refactoring tomorrow if it's okay for you @maschnetwork.

**Comment by embano1** [comment]
@agebhar1 should be separate issue
